version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_TLS: 'false'
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      ADJOE_SDK_HASH: ${ADJOE_SDK_HASH}
      ADJOE_S2S_TOKEN: ${ADJOE_S2S_TOKEN}
      PAYPAL_MODE: live
      PAYPAL_LIVE_CLIENT_ID: ${PAYPAL_LIVE_CLIENT_ID}
      PAYPAL_LIVE_SECRET: ${PAYPAL_LIVE_SECRET}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      ADMIN_URL: ${ADMIN_URL}
    depends_on:
      - redis
    restart: unless-stopped

  prisma-studio:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install -g prisma@5.22.0 && prisma studio --schema ./prisma/schema.prisma --port 5555 --hostname 0.0.0.0 --browser none"
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: ${DO_DATABASE_URL}
    volumes:
      - ./apps/api/prisma:/app/prisma
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - '3001:3001'
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: swecash
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
